name: Validate Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo        
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '>=1.6.5'

    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10'
   
    # - name: Pip install
    #   run: pip3 install databricks-cli --upgrade

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Validate login
      run: az account show
      shell: bash

    - name: Init & Import
      run: ./sh_scripts/3init_terraform.sh
      continue-on-error: true
      shell: bash
    
    - name: Validation step
      if: always()
      run: ./sh_scripts/4validate_terraform.sh
      shell: bash

    - name: Deployment step
      if: always()
      run: ./sh_scripts/5deploy_terraform.sh
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Azure logout
      if: always()
      run: bash az logout
